version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./app/reverse-proxy/nginx/conf.d:/etc/nginx/conf.d
      - ./app/reverse-proxy/certs:/etc/letsencrypt
      - ./app/reverse-proxy/certs-data:/data/letsencrypt
      - certbot-etc:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

  frontend:
    build:
      context: ./app/frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./app/backend
    expose:
      - "8000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_SECRET}@mongo:27017/app?authSource=admin
    networks:
      - appnet

  mongo:
    image: mongo:7
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - ./app/database/mongod.conf:/etc/mongod.conf
      - ./app/database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    env_file:
      - .env
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - appnet

volumes:
  mongo_data:
  certs:
  certs-data:
  certbot-etc:

networks:
  appnet:
