version: '3.9'

services:
  certgen:
    image: alpine:latest
    volumes:
      - ./app/reverse-proxy/certs:/certs
    entrypoint: >
      sh -c "
        apk add --no-cache openssl &&
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /certs/key.pem \
          -out /certs/cert.pem \
          -subj '/CN=localhost'
      "
    restart: "no"

  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./app/reverse-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app/reverse-proxy/certs:/etc/nginx/certs
    depends_on:
      - certgen
      - frontend
      - backend
    networks:
      - appnet

  frontend:
    build:
      context: ./app/frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./app/backend
    expose:
      - "8000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_SECRET}@mongo:27017/app?authSource=admin
    networks:
      - appnet

  mongo:
    image: mongo:7
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - ./app/database/mongod.conf:/etc/mongod.conf
      - ./app/database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    env_file:
      - .env
    command: ["mongod", "--config", "/etc/mongod.conf"]
    networks:
      - appnet

volumes:
  mongo_data:
  certs:

networks:
  appnet:
